### ISSUE TITLE
Feature request: create polymer style module called px-buttons-shared-styles (similar to colors-shared-styles.html)

### ISSUE THREAD

**Issue by cherukumilli** [predixdesignsystem/px-buttons-design#13]
Currently there is no style module available for `px-buttons-design`.
It would be great if all the design projects come with a polymer style module.

I only see a style module for `px-colors-design` and it is called `colors-shared-styles`.

is there any way the predix design team can create style modules for all the design related bower components like `px-defaults-design`, `px-forms-design`, `px-functions-design`, etc...

This will also prevent copies of the same styles from getting into multiple web components.
For example:
`px-spinner` depends on design styles
- px-normalize-design
- **px-box-sizing-design**
- **px-helpers-design**
- px-flexbox-design
- px-buttons-design
- px-headings-design

`px-modal` depends on design styles
- **px-box-sizing-design**
- **px-helpers-design**
- px-normalize-design

Style modules are created for both the web components. The style modules have duplicate copies of the `px-box-sizing-design` and `px-helpers-design` styles.

Most of the predix web components have copies of the styles in them making them a little bigger.

If we use style modules for design then we use browser caching to download it only once and reuse it across multiple elements (like `colors-shared-styles`).

**Comment by cherukumilli** [comment]
@randyaskin 
Can you please chime in on this request?

**Comment by mdwragg** [comment]
Hi @cherukumilli,

While an interesting idea, you're talking about a large scale re-architecture of how we build & ship our components. We don't have the time for that right now.

Your postulation about reducing size by sharing of style modules assumes that (for example) we load *all* button styles into a given components style module. in reality we only load a subset of each design sass file into a component as we only switch on flags (and hence pieces of sass) pertinent to a component. e.g. range picker may load buttons but only enable primary and secondary (not tertiary, iconic, disabled etc.), meaning we only include a percentage of a given 'design' repos sass per component.

PRs are always welcome, though. If you've got the time and inclination, and can figure out a way to automatically generate the style module for each design repo as part of the default gulp build for each one I'd be happy to take a look at the PR.

Thanks.

p.s. I put one of our components through the 'polymer modulizer' for Polymer 3. It made a crazy mess of the style modules (turning them into js files). No idea what the accepted way to handle this is in Polymer 3. It'll be CSS-in-JS over my dead body ;-)
